# coding: utf-8

"""
    Doslano Integration API

    Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from doslano.models.webhook_event import WebhookEvent

class TestWebhookEvent(unittest.TestCase):
    """WebhookEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookEvent:
        """Test WebhookEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookEvent`
        """
        model = WebhookEvent()
        if include_optional:
            return WebhookEvent(
                id = '',
                type = 'letter.sent',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data = doslano.models.webhook_event_data.WebhookEvent_data(
                    letter_id = '', 
                    recipient_id = '', 
                    status = '', 
                    shipment_number = '', 
                    tracking_number = '', 
                    error = '', )
            )
        else:
            return WebhookEvent(
                id = '',
                type = 'letter.sent',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data = doslano.models.webhook_event_data.WebhookEvent_data(
                    letter_id = '', 
                    recipient_id = '', 
                    status = '', 
                    shipment_number = '', 
                    tracking_number = '', 
                    error = '', ),
        )
        """

    def testWebhookEvent(self):
        """Test WebhookEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
