# coding: utf-8

"""
    Doslano Integration API

    Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from doslano.models.letter import Letter

class TestLetter(unittest.TestCase):
    """Letter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Letter:
        """Test Letter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Letter`
        """
        model = Letter()
        if include_optional:
            return Letter(
                id = '',
                channel = 'web',
                status = 'forming',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sender = doslano.models.party.Party(
                    name = '', 
                    address = '', 
                    party_type = 'individual', 
                    inn = '', ),
                recipients = [
                    doslano.models.recipient.Recipient(
                        id = '', 
                        name = '', 
                        address = '', 
                        status = 'pending', 
                        shipment_number = '', 
                        tracking_number = '', 
                        price_minor = 56, 
                        error = '', 
                        receipt_pdf = '', 
                        receipt_url = '', 
                        inventory_pdf = '', )
                    ],
                pricing = doslano.models.pricing.Pricing(
                    total_minor = 56, 
                    currency = 'RUB', 
                    promo = doslano.models.promo_result.PromoResult(
                        code = '', 
                        applied = True, 
                        discount_minor = 56, 
                        message = '', ), ),
                payment = doslano.models.payment_result.PaymentResult(
                    charged = True, 
                    status = 'paid', ),
                callback_url = ''
            )
        else:
            return Letter(
                id = '',
                channel = 'web',
                status = 'forming',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                recipients = [
                    doslano.models.recipient.Recipient(
                        id = '', 
                        name = '', 
                        address = '', 
                        status = 'pending', 
                        shipment_number = '', 
                        tracking_number = '', 
                        price_minor = 56, 
                        error = '', 
                        receipt_pdf = '', 
                        receipt_url = '', 
                        inventory_pdf = '', )
                    ],
                pricing = doslano.models.pricing.Pricing(
                    total_minor = 56, 
                    currency = 'RUB', 
                    promo = doslano.models.promo_result.PromoResult(
                        code = '', 
                        applied = True, 
                        discount_minor = 56, 
                        message = '', ), ),
        )
        """

    def testLetter(self):
        """Test Letter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
