# coding: utf-8

"""
    Doslano Integration API

    Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from doslano.models.create_letter_request import CreateLetterRequest

class TestCreateLetterRequest(unittest.TestCase):
    """CreateLetterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateLetterRequest:
        """Test CreateLetterRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateLetterRequest`
        """
        model = CreateLetterRequest()
        if include_optional:
            return CreateLetterRequest(
                sender = doslano.models.sender_input.SenderInput(
                    name = '', 
                    address = '', 
                    email = '', 
                    party_type = 'individual', 
                    inn = '480728880015', ),
                recipients = [
                    doslano.models.recipient_input.RecipientInput(
                        name = '', 
                        address = '', 
                        party_type = 'individual', 
                        inn = '0480728880', 
                        email = '', 
                        resolve_address_by_inn = True, )
                    ],
                content = doslano.models.letter_content.LetterContent(
                    main_file = doslano.models.file_source.FileSource(
                        base64 = '', 
                        url = '', 
                        filename = '', ), 
                    attachments = [
                        doslano.models.file_source.FileSource(
                            base64 = '', 
                            url = '', 
                            filename = '', )
                        ], ),
                letter_class = 'registered',
                promo_code = '',
                on_promo_invalid = 'ignore',
                on_insufficient_funds = 'reject',
                dry_run = True,
                callback_url = ''
            )
        else:
            return CreateLetterRequest(
                recipients = [
                    doslano.models.recipient_input.RecipientInput(
                        name = '', 
                        address = '', 
                        party_type = 'individual', 
                        inn = '0480728880', 
                        email = '', 
                        resolve_address_by_inn = True, )
                    ],
                content = doslano.models.letter_content.LetterContent(
                    main_file = doslano.models.file_source.FileSource(
                        base64 = '', 
                        url = '', 
                        filename = '', ), 
                    attachments = [
                        doslano.models.file_source.FileSource(
                            base64 = '', 
                            url = '', 
                            filename = '', )
                        ], ),
        )
        """

    def testCreateLetterRequest(self):
        """Test CreateLetterRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
