# coding: utf-8

"""
    Doslano Integration API

    Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from doslano.api.letters_api import LettersApi


class TestLettersApi(unittest.TestCase):
    """LettersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LettersApi()

    def tearDown(self) -> None:
        pass

    def test_create_letter(self) -> None:
        """Test case for create_letter

        Отправить письмо
        """
        pass

    def test_get_letter(self) -> None:
        """Test case for get_letter

        Статус письма
        """
        pass

    def test_get_recipient_tracking(self) -> None:
        """Test case for get_recipient_tracking

        Трек-события получателя
        """
        pass

    def test_list_letters(self) -> None:
        """Test case for list_letters

        Список писем
        """
        pass


if __name__ == '__main__':
    unittest.main()
