# coding: utf-8

"""
    Doslano Integration API

    Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from doslano.models.webhook_event import WebhookEvent

from doslano.api_client import ApiClient, RequestSerialized
from doslano.api_response import ApiResponse
from doslano.rest import RESTResponseType


class DefaultApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def on_letter_status_changed(
        self,
        webhook_event: ,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Колбек на финальный статус

        Если при отправке письма указан `callback_url`, мы шлём на него POST при достижении финального статуса — по каждому получателю (`recipient.sent` / `recipient.failed`) и агрегатно по письму (`letter.sent` / `letter.partial_failure` / `letter.failed` / `letter.cancelled`).  Отдельный случай `letter.cancelled` — когда адрес/ФИО не прошли проверку Почты России **уже после** ответа `201` (поздний preflight: проверка не успела завершиться в окне синхронного ответа). Письмо отменяется автоматически, в `data.error` — перечень полей с ошибками; исправьте данные и создайте письмо заново. Если же ошибка адреса выявлена **сразу** при создании — вы получаете её синхронно (HTTP 422 `address_validation_failed`), и колбек по такому письму НЕ шлётся. То есть на одно письмо приходит ровно один сигнал об адресной ошибке: либо синхронный 422, либо асинхронный `letter.cancelled`.  **Подпись.** Заголовок `X-Doslano-Signature: t=<unix>,v1=<hex>` — где `v1 = HMAC_SHA256(secret, \"<t>.\" + raw_body)`, `secret` — секрет аккаунта из ЛК (раздел «API»). Проверьте подпись и свежесть `t` (±5 мин).  **Доставка.** At-least-once: ждём ответ `2xx`; иначе ретраим по нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем как недоставленный (видно в ЛК, можно переотправить). Дедуп — по `id` события. Порядок не гарантируется — сверяйтесь со `status` в теле. 

        :param webhook_event: (required)
        :type webhook_event: WebhookEvent
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._on_letter_status_changed_serialize(
            webhook_event=webhook_event,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def on_letter_status_changed_with_http_info(
        self,
        webhook_event: ,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Колбек на финальный статус

        Если при отправке письма указан `callback_url`, мы шлём на него POST при достижении финального статуса — по каждому получателю (`recipient.sent` / `recipient.failed`) и агрегатно по письму (`letter.sent` / `letter.partial_failure` / `letter.failed` / `letter.cancelled`).  Отдельный случай `letter.cancelled` — когда адрес/ФИО не прошли проверку Почты России **уже после** ответа `201` (поздний preflight: проверка не успела завершиться в окне синхронного ответа). Письмо отменяется автоматически, в `data.error` — перечень полей с ошибками; исправьте данные и создайте письмо заново. Если же ошибка адреса выявлена **сразу** при создании — вы получаете её синхронно (HTTP 422 `address_validation_failed`), и колбек по такому письму НЕ шлётся. То есть на одно письмо приходит ровно один сигнал об адресной ошибке: либо синхронный 422, либо асинхронный `letter.cancelled`.  **Подпись.** Заголовок `X-Doslano-Signature: t=<unix>,v1=<hex>` — где `v1 = HMAC_SHA256(secret, \"<t>.\" + raw_body)`, `secret` — секрет аккаунта из ЛК (раздел «API»). Проверьте подпись и свежесть `t` (±5 мин).  **Доставка.** At-least-once: ждём ответ `2xx`; иначе ретраим по нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем как недоставленный (видно в ЛК, можно переотправить). Дедуп — по `id` события. Порядок не гарантируется — сверяйтесь со `status` в теле. 

        :param webhook_event: (required)
        :type webhook_event: WebhookEvent
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._on_letter_status_changed_serialize(
            webhook_event=webhook_event,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def on_letter_status_changed_without_preload_content(
        self,
        webhook_event: ,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Колбек на финальный статус

        Если при отправке письма указан `callback_url`, мы шлём на него POST при достижении финального статуса — по каждому получателю (`recipient.sent` / `recipient.failed`) и агрегатно по письму (`letter.sent` / `letter.partial_failure` / `letter.failed` / `letter.cancelled`).  Отдельный случай `letter.cancelled` — когда адрес/ФИО не прошли проверку Почты России **уже после** ответа `201` (поздний preflight: проверка не успела завершиться в окне синхронного ответа). Письмо отменяется автоматически, в `data.error` — перечень полей с ошибками; исправьте данные и создайте письмо заново. Если же ошибка адреса выявлена **сразу** при создании — вы получаете её синхронно (HTTP 422 `address_validation_failed`), и колбек по такому письму НЕ шлётся. То есть на одно письмо приходит ровно один сигнал об адресной ошибке: либо синхронный 422, либо асинхронный `letter.cancelled`.  **Подпись.** Заголовок `X-Doslano-Signature: t=<unix>,v1=<hex>` — где `v1 = HMAC_SHA256(secret, \"<t>.\" + raw_body)`, `secret` — секрет аккаунта из ЛК (раздел «API»). Проверьте подпись и свежесть `t` (±5 мин).  **Доставка.** At-least-once: ждём ответ `2xx`; иначе ретраим по нарастающему графику (несколько попыток в течение ~24 ч), затем помечаем как недоставленный (видно в ЛК, можно переотправить). Дедуп — по `id` события. Порядок не гарантируется — сверяйтесь со `status` в теле. 

        :param webhook_event: (required)
        :type webhook_event: WebhookEvent
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._on_letter_status_changed_serialize(
            webhook_event=webhook_event,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _on_letter_status_changed_serialize(
        self,
        webhook_event,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if webhook_event is not None:
            _body_params = webhook_event



        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/letterStatusChanged',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


