# coding: utf-8

# flake8: noqa
"""
    Doslano Integration API

    Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from doslano.models.balance import Balance
from doslano.models.create_letter_request import CreateLetterRequest
from doslano.models.file_source import FileSource
from doslano.models.letter import Letter
from doslano.models.letter_class import LetterClass
from doslano.models.letter_content import LetterContent
from doslano.models.letter_status import LetterStatus
from doslano.models.list_letters200_response import ListLetters200Response
from doslano.models.party import Party
from doslano.models.party_type import PartyType
from doslano.models.payment_result import PaymentResult
from doslano.models.pricing import Pricing
from doslano.models.problem import Problem
from doslano.models.promo_result import PromoResult
from doslano.models.recipient import Recipient
from doslano.models.recipient_input import RecipientInput
from doslano.models.recipient_status import RecipientStatus
from doslano.models.sender_input import SenderInput
from doslano.models.tracking_info import TrackingInfo
from doslano.models.tracking_info_events_inner import TrackingInfoEventsInner
from doslano.models.webhook_event import WebhookEvent
from doslano.models.webhook_event_data import WebhookEventData
