# coding: utf-8

"""
    Doslano Integration API

    Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from doslano.models.letter_class import LetterClass
from doslano.models.letter_content import LetterContent
from doslano.models.recipient_input import RecipientInput
from doslano.models.sender_input import SenderInput
from typing import Optional, Set
from typing_extensions import Self

class CreateLetterRequest(BaseModel):
    """
    CreateLetterRequest
    """ # noqa: E501
    sender: Optional[SenderInput] = Field(default=None, description="Отправитель. Если не указан — берётся отправитель по умолчанию из профиля аккаунта.")
    recipients: Annotated[List[RecipientInput], Field(min_length=1, max_length=20)]
    content: LetterContent
    letter_class: Optional[LetterClass] = LetterClass.REGISTERED
    promo_code: Optional[StrictStr] = Field(default=None, description="Промокод (опционально).")
    on_promo_invalid: Optional[StrictStr] = Field(default='ignore', description="Что делать, если промокод не применился: `ignore` — отправить без скидки и вернуть пометку в `pricing.promo`; `reject` — отклонить (422). ")
    on_insufficient_funds: Optional[StrictStr] = Field(default='reject', description="Что делать при нехватке средств: `reject` — отклонить (402), письмо не создаётся; `hold` — создать письмо в статусе `awaiting_payment`, оно оплатится автоматически при пополнении баланса. ")
    callback_url: Optional[StrictStr] = Field(default=None, description="HTTPS-URL для колбеков по этому письму. Если не указан — используйте поллинг.")
    __properties: ClassVar[List[str]] = ["sender", "recipients", "content", "letter_class", "promo_code", "on_promo_invalid", "on_insufficient_funds", "callback_url"]

    @field_validator('on_promo_invalid')
    def on_promo_invalid_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ignore', 'reject']):
            raise ValueError("must be one of enum values ('ignore', 'reject')")
        return value

    @field_validator('on_insufficient_funds')
    def on_insufficient_funds_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['reject', 'hold']):
            raise ValueError("must be one of enum values ('reject', 'hold')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateLetterRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sender
        if self.sender:
            _dict['sender'] = self.sender.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recipients (list)
        _items = []
        if self.recipients:
            for _item_recipients in self.recipients:
                if _item_recipients:
                    _items.append(_item_recipients.to_dict())
            _dict['recipients'] = _items
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict['content'] = self.content.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateLetterRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sender": SenderInput.from_dict(obj["sender"]) if obj.get("sender") is not None else None,
            "recipients": [RecipientInput.from_dict(_item) for _item in obj["recipients"]] if obj.get("recipients") is not None else None,
            "content": LetterContent.from_dict(obj["content"]) if obj.get("content") is not None else None,
            "letter_class": obj.get("letter_class") if obj.get("letter_class") is not None else LetterClass.REGISTERED,
            "promo_code": obj.get("promo_code"),
            "on_promo_invalid": obj.get("on_promo_invalid") if obj.get("on_promo_invalid") is not None else 'ignore',
            "on_insufficient_funds": obj.get("on_insufficient_funds") if obj.get("on_insufficient_funds") is not None else 'reject',
            "callback_url": obj.get("callback_url")
        })
        return _obj


