# coding: utf-8

"""
    Doslano Integration API

    Публичный REST API doslano: отправка заказных писем одним запросом, проверка статуса и трек-номеров (наш РПО + Почты России), баланс, колбеки на финальный статус письма.  **Авторизация** — API-ключ в заголовке `Authorization: Bearer dl_live_…`. Ключи и журнал активности — в ЛК, раздел «API». Ключ имеет набор прав (scopes) и (опционально) IP-allowlist.  **Оплата** — только с баланса аккаунта (предоплата). Пополнение — в ЛК.  **Колбеки** — необязательный `callback_url` указывается при отправке каждого письма; иначе используйте поллинг `GET /v1/letters/{id}`. Тело колбека подписывается HMAC-SHA256 секретом аккаунта (заголовок `X-Doslano-Signature`).  Это дополнительный интерфейс доступа к тем же услугам; использование регулируется действующей офертой личного кабинета doslano. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from doslano.models.recipient_status import RecipientStatus
from typing import Optional, Set
from typing_extensions import Self

class Recipient(BaseModel):
    """
    Recipient
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    address: Optional[StrictStr] = None
    status: RecipientStatus
    shipment_number: Optional[StrictStr] = Field(default=None, description="Наш трек-номер (РПО), присваивается сразу при создании.")
    tracking_number: Optional[StrictStr] = Field(default=None, description="Трек-номер Почты России (ШПИ). Появляется после регистрации отправления.")
    price_minor: Optional[StrictInt] = Field(default=None, description="Стоимость отправления этому получателю, в копейках.")
    error: Optional[StrictStr] = Field(default=None, description="Причина ошибки (для `failed`).")
    receipt_pdf: Optional[StrictStr] = Field(default=None, description="Ссылка на скачивание PDF фискального чека (54-ФЗ) этому получателю через наш API (см. `GET /v1/letters/{id}/recipients/{recipient_id}/receipt.pdf`). Присутствует, только когда чек пробит и его PDF сохранён у нас (получатель в статусе `sent`/`delivered`).")
    receipt_url: Optional[StrictStr] = Field(default=None, description="Ссылка на фискальный чек на сайте ОФД (1-ОФД). Присутствует, когда чек пробит (получатель `sent`/`delivered`). Может присутствовать и без `receipt_pdf` — когда наш PDF недоступен (link_only).")
    inventory_pdf: Optional[StrictStr] = Field(default=None, description="Ссылка на скачивание PDF описи вложения (форма 107, версия отправителя) через наш API (см. `GET /v1/letters/{id}/recipients/{recipient_id}/inventory.pdf`). Присутствует, когда опись сформирована и отправление передано в Почту (получатель в статусе `sent`/`delivered`).")
    __properties: ClassVar[List[str]] = ["id", "name", "address", "status", "shipment_number", "tracking_number", "price_minor", "error", "receipt_pdf", "receipt_url", "inventory_pdf"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Recipient from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Recipient from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "address": obj.get("address"),
            "status": obj.get("status"),
            "shipment_number": obj.get("shipment_number"),
            "tracking_number": obj.get("tracking_number"),
            "price_minor": obj.get("price_minor"),
            "error": obj.get("error"),
            "receipt_pdf": obj.get("receipt_pdf"),
            "receipt_url": obj.get("receipt_url"),
            "inventory_pdf": obj.get("inventory_pdf")
        })
        return _obj


